In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy.random as rd

----------------

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.shape(arr)

(3, 3)

In [6]:
arr = np.arange(1,25).reshape(4, 3, 2)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [7]:
arr = np.zeros((3, 4), dtype=str)
arr

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [8]:
arr = np.ones((3,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [9]:
arr = rd.randint(1, 101, size = [2, 10, 15])
print(arr)

[[[ 84  57  67  34  16  58  79  29  60  71  27  10  96  65  63]
  [ 76  35  53  71  33  82  91   1  21  93  32  97   7   6  60]
  [ 55  62  71 100  39  69  32  78  86  15  70  25  13  69  78]
  [ 54 100  75  70  72   1  58  88  72  97  93  24  65  97   4]
  [ 97  73  99  14  37  50  36  32  62  94  99  55  58  42  86]
  [ 92  38  43  35  40  49  99  28  14  14  73  27  26  65  18]
  [ 15  60  69  33  79  81  77  54  52  52  65  71  26  13  40]
  [ 75  68  34  29  15  22   7  50  64  57  29  59  34  50  62]
  [ 77  58  94  95  71  72  15  48  71  20  21  37  48  85  81]
  [ 21  24  86  77  81  76  81  47  55  25  76  73  32  30  55]]

 [[ 55  68  29  86  84   5  44  13  24  75  82  42   9  45  58]
  [ 81   1  24   6  44  65  75  97  38  94  70  94  19  87  54]
  [ 64  38   9  89  46  53  57  59   8  70  95  89   9  58  30]
  [ 78  62  56  14  85  37  10  19  47  65  64  51  91  44  22]
  [ 40  36  19  12  43  66  42  33  79  13  67  76  33  45  76]
  [ 86  37  44  45  82  68  72  76  58

In [10]:
arr1 = rd.randint(1, 101, size = [5,7],)
print(arr1)

[[ 8 80 41  3 43 86 89]
 [43 36 22 71 44 48  6]
 [34 90 50 20 37 88 63]
 [28 84 20 46 93 76 12]
 [ 6 60 34 19 74 50 15]]


In [17]:
arr1 = rd.choice(np.arange(101), size = [3, 3, 4, 4])
print(arr1)

[[[[ 38  19  15  51]
   [ 42  65  59  40]
   [ 87  89  62  75]
   [ 35   1  23  28]]

  [[ 92  19  41   3]
   [ 78  43  34  23]
   [ 98   4  68  40]
   [ 24  56  34  34]]

  [[ 73  41  20  57]
   [ 16  54  66  68]
   [ 15  19  55  98]
   [ 73   6  11  66]]]


 [[[ 42  22  77  50]
   [ 61   8  43  75]
   [  7  82  18  40]
   [ 11  81  81  27]]

  [[ 41  29  13 100]
   [ 24  91  77  90]
   [ 85  28  76  14]
   [ 97  20  53  98]]

  [[ 66  47  26   3]
   [ 33  57   8  48]
   [ 94  38  11  80]
   [ 23  65  66  32]]]


 [[[ 84  12  28   3]
   [ 53  44  20  72]
   [ 93  66  39  64]
   [ 93  22  67  78]]

  [[ 16  45  24  24]
   [ 60  71  94  21]
   [ 47  76  51  60]
   [ 29  62  36  61]]

  [[ 92  23  31  64]
   [ 85  70  91  95]
   [ 19  86   4  96]
   [ 34  92   0  75]]]]


In [19]:
rd.choice(arr1.flatten(), size = [3, 4])

array([[ 85,  42,  54,  86],
       [100,  92,   8,  23],
       [ 95,  40,  44,  20]])

In [20]:
rd.rand(3,5)

array([[0.00697051, 0.63848553, 0.23166428, 0.94789171, 0.04029223],
       [0.20913303, 0.2980383 , 0.11513867, 0.79791707, 0.37289962],
       [0.313803  , 0.7045349 , 0.29821943, 0.21724399, 0.65067597]])

In [21]:
rd.randint(1, 101, size = [3, 5])

array([[52, 20, 73, 79, 81],
       [14, 35, 43, 28, 65],
       [98, 83, 16, 89, 62]])

In [22]:
rd.uniform(1, 101, size = [3, 5])

array([[76.51571095,  6.48595304, 62.21111235, 83.61771374, 21.88554611],
       [64.18515404, 54.10143095, 68.24545714, 82.66606161, 94.26502194],
       [ 7.05978396, 27.43041987, 23.33480423, 56.53702018, 97.50475193]])

In [23]:
x = np.array([54,85,46,95,21,47,35,29], ndmin=5, dtype=float)
print(x)

[[[[[54. 85. 46. 95. 21. 47. 35. 29.]]]]]


In [24]:
np.max(x)

95.0

In [25]:
np.min(x)

21.0

In [26]:
np.argmin(x)

4

In [27]:
np.argmax(x)

3

In [28]:
np.mean(arr)

52.29666666666667

In [29]:
np.median(arr)

54.5

In [30]:
np.std(arr)

27.073147623101054

In [31]:
np.var(arr)

732.9553222222222

In [32]:
np.power(x, x)

array([[[[[3.54211805e+093, 1.00140253e+164, 3.06803463e+076,
           7.65142812e+187, 5.84258702e+027, 3.87792426e+078,
           1.10250750e+054, 2.56768615e+042]]]]])

In [39]:
x = arr.flatten()
print(x)

[ 84  57  67  34  16  58  79  29  60  71  27  10  96  65  63  76  35  53
  71  33  82  91   1  21  93  32  97   7   6  60  55  62  71 100  39  69
  32  78  86  15  70  25  13  69  78  54 100  75  70  72   1  58  88  72
  97  93  24  65  97   4  97  73  99  14  37  50  36  32  62  94  99  55
  58  42  86  92  38  43  35  40  49  99  28  14  14  73  27  26  65  18
  15  60  69  33  79  81  77  54  52  52  65  71  26  13  40  75  68  34
  29  15  22   7  50  64  57  29  59  34  50  62  77  58  94  95  71  72
  15  48  71  20  21  37  48  85  81  21  24  86  77  81  76  81  47  55
  25  76  73  32  30  55  55  68  29  86  84   5  44  13  24  75  82  42
   9  45  58  81   1  24   6  44  65  75  97  38  94  70  94  19  87  54
  64  38   9  89  46  53  57  59   8  70  95  89   9  58  30  78  62  56
  14  85  37  10  19  47  65  64  51  91  44  22  40  36  19  12  43  66
  42  33  79  13  67  76  33  45  76  86  37  44  45  82  68  72  76  58
  28  30  79  84  64  84   3  92  46  91  15  28  9

In [40]:
np.sort(x)

array([  1,   1,   1,   2,   3,   4,   4,   5,   5,   6,   6,   7,   7,
         7,   8,   8,   9,   9,   9,  10,  10,  10,  11,  12,  12,  13,
        13,  13,  13,  13,  13,  14,  14,  14,  14,  15,  15,  15,  15,
        15,  16,  16,  17,  18,  19,  19,  19,  20,  21,  21,  21,  22,
        22,  24,  24,  24,  24,  25,  25,  25,  26,  26,  27,  27,  28,
        28,  28,  29,  29,  29,  29,  29,  30,  30,  30,  32,  32,  32,
        32,  33,  33,  33,  33,  33,  34,  34,  34,  35,  35,  35,  36,
        36,  36,  36,  36,  36,  37,  37,  37,  37,  38,  38,  38,  38,
        39,  39,  40,  40,  40,  40,  42,  42,  42,  42,  42,  42,  43,
        43,  43,  44,  44,  44,  44,  44,  45,  45,  45,  46,  46,  47,
        47,  48,  48,  48,  48,  49,  50,  50,  50,  50,  50,  51,  52,
        52,  53,  53,  54,  54,  54,  54,  55,  55,  55,  55,  55,  55,
        56,  56,  56,  57,  57,  57,  57,  58,  58,  58,  58,  58,  58,
        58,  59,  59,  60,  60,  60,  62,  62,  62,  62,  62,  6

In [44]:
(np.sort(x))[::-1]

array([100, 100,  99,  99,  99,  97,  97,  97,  97,  97,  96,  96,  96,
        95,  95,  94,  94,  94,  94,  93,  93,  93,  92,  92,  92,  91,
        91,  91,  89,  89,  88,  87,  87,  86,  86,  86,  86,  86,  85,
        85,  84,  84,  84,  84,  84,  82,  82,  82,  81,  81,  81,  81,
        81,  81,  81,  81,  79,  79,  79,  79,  78,  78,  78,  77,  77,
        77,  77,  76,  76,  76,  76,  76,  76,  76,  75,  75,  75,  75,
        75,  73,  73,  73,  72,  72,  72,  72,  71,  71,  71,  71,  71,
        71,  70,  70,  70,  70,  69,  69,  69,  68,  68,  68,  68,  68,
        67,  67,  67,  66,  65,  65,  65,  65,  65,  65,  64,  64,  64,
        64,  63,  63,  62,  62,  62,  62,  62,  60,  60,  60,  59,  59,
        58,  58,  58,  58,  58,  58,  58,  57,  57,  57,  57,  56,  56,
        56,  55,  55,  55,  55,  55,  55,  54,  54,  54,  54,  53,  53,
        52,  52,  51,  50,  50,  50,  50,  50,  49,  48,  48,  48,  48,
        47,  47,  46,  46,  45,  45,  45,  44,  44,  44,  44,  4

In [51]:
x.reshape(1,-1)

array([[ 84,  57,  67,  34,  16,  58,  79,  29,  60,  71,  27,  10,  96,
         65,  63,  76,  35,  53,  71,  33,  82,  91,   1,  21,  93,  32,
         97,   7,   6,  60,  55,  62,  71, 100,  39,  69,  32,  78,  86,
         15,  70,  25,  13,  69,  78,  54, 100,  75,  70,  72,   1,  58,
         88,  72,  97,  93,  24,  65,  97,   4,  97,  73,  99,  14,  37,
         50,  36,  32,  62,  94,  99,  55,  58,  42,  86,  92,  38,  43,
         35,  40,  49,  99,  28,  14,  14,  73,  27,  26,  65,  18,  15,
         60,  69,  33,  79,  81,  77,  54,  52,  52,  65,  71,  26,  13,
         40,  75,  68,  34,  29,  15,  22,   7,  50,  64,  57,  29,  59,
         34,  50,  62,  77,  58,  94,  95,  71,  72,  15,  48,  71,  20,
         21,  37,  48,  85,  81,  21,  24,  86,  77,  81,  76,  81,  47,
         55,  25,  76,  73,  32,  30,  55,  55,  68,  29,  86,  84,   5,
         44,  13,  24,  75,  82,  42,   9,  45,  58,  81,   1,  24,   6,
         44,  65,  75,  97,  38,  94,  70,  94,  19

In [55]:
x.reshape(-1,1)

array([[ 84],
       [ 57],
       [ 67],
       [ 34],
       [ 16],
       [ 58],
       [ 79],
       [ 29],
       [ 60],
       [ 71],
       [ 27],
       [ 10],
       [ 96],
       [ 65],
       [ 63],
       [ 76],
       [ 35],
       [ 53],
       [ 71],
       [ 33],
       [ 82],
       [ 91],
       [  1],
       [ 21],
       [ 93],
       [ 32],
       [ 97],
       [  7],
       [  6],
       [ 60],
       [ 55],
       [ 62],
       [ 71],
       [100],
       [ 39],
       [ 69],
       [ 32],
       [ 78],
       [ 86],
       [ 15],
       [ 70],
       [ 25],
       [ 13],
       [ 69],
       [ 78],
       [ 54],
       [100],
       [ 75],
       [ 70],
       [ 72],
       [  1],
       [ 58],
       [ 88],
       [ 72],
       [ 97],
       [ 93],
       [ 24],
       [ 65],
       [ 97],
       [  4],
       [ 97],
       [ 73],
       [ 99],
       [ 14],
       [ 37],
       [ 50],
       [ 36],
       [ 32],
       [ 62],
       [ 94],
       [ 99],
      