In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy.random as rd

----------------

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.shape(arr)

(3, 3)

In [8]:
arr = np.arange(1,25).reshape(4, 3, 2)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [13]:
arr = np.zeros((3, 4), dtype=str)
arr

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [14]:
arr = np.ones((3,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [15]:
arr = rd.randint(1, 101, size = [5, 10, 25])
print(arr)

[[[ 93  96  31 ...   2  85  18]
  [ 94  23  55 ...  21  65  46]
  [ 89  60  30 ...  75  63  87]
  ...
  [ 79   4  75 ...  78  82  33]
  [100  34  38 ...  27  26  28]
  [  5   3  18 ...  76  71  65]]

 [[ 10  73  34 ...  64  49  91]
  [ 95  28  86 ...   8  95  46]
  [100  19  30 ...  33  36  61]
  ...
  [ 20  39  47 ...   1  73  42]
  [ 45  49  38 ...  85  17  89]
  [ 17   6  88 ...  95  20  68]]

 [[ 14  87  98 ...  99  22   5]
  [ 87  84  75 ...  54  85  98]
  [ 61   7  90 ...  68  38  82]
  ...
  [ 14  35  19 ...   7  20  28]
  [ 10  82  66 ...  33  41  42]
  [ 67  41  67 ...  15   9  39]]

 [[ 55  28  17 ...  25  55  71]
  [ 52  78  55 ...  93  98  89]
  [  6  85   5 ...   1  63  91]
  ...
  [ 72  64  68 ...  92  83  38]
  [ 18  80  13 ...  53  81  76]
  [ 47   2  74 ...  46  51  27]]

 [[ 19  76  96 ...  16  14  78]
  [ 11  82  82 ...  92  62  39]
  [ 56  12   2 ...  99  47  21]
  ...
  [ 63  13  16 ... 100  98  68]
  [ 83  61  37 ...   5  30  27]
  [ 74  10  51 ...  29  49  96]]]


In [16]:
arr2 = rd.randint(1, 101, size = [24])
print(arr2)

[ 85  97  15  62  39  88  47 100  94   6  78  22  20  21  16  44  65  96
   2  34  20  67  19  85]


In [17]:
rd.choice([1, 2, 3, 4, 5], size = [3, 3, 4, 4] )

array([[[[4, 3, 2, 5],
         [2, 1, 5, 3],
         [3, 5, 3, 4],
         [1, 5, 1, 5]],

        [[3, 2, 1, 5],
         [4, 2, 4, 5],
         [2, 4, 3, 3],
         [4, 3, 4, 3]],

        [[3, 3, 2, 4],
         [2, 5, 3, 2],
         [5, 5, 3, 3],
         [2, 4, 1, 5]]],


       [[[1, 3, 5, 1],
         [3, 1, 3, 1],
         [5, 2, 4, 1],
         [3, 1, 3, 2]],

        [[3, 3, 4, 3],
         [5, 3, 4, 4],
         [3, 3, 4, 3],
         [2, 4, 1, 1]],

        [[2, 2, 3, 3],
         [1, 5, 2, 5],
         [1, 4, 1, 3],
         [2, 1, 1, 5]]],


       [[[4, 1, 3, 5],
         [5, 1, 1, 1],
         [3, 4, 3, 4],
         [1, 3, 3, 1]],

        [[3, 4, 1, 3],
         [2, 2, 5, 3],
         [4, 3, 2, 4],
         [4, 2, 2, 5]],

        [[4, 5, 5, 2],
         [5, 3, 3, 5],
         [4, 3, 2, 3],
         [4, 3, 2, 5]]]])

In [18]:
rd.choice(arr2, size = [3, 4], replace = False)

array([[ 15,  62,  20, 100],
       [ 21,  85,  16,  39],
       [ 20,  34,  96,  78]])

In [19]:
rd.rand(3,5)

array([[0.79947696, 0.70887155, 0.69478949, 0.57152222, 0.85057083],
       [0.61272501, 0.30366138, 0.4440806 , 0.0375269 , 0.45019837],
       [0.47952587, 0.79503645, 0.21154503, 0.1561328 , 0.51044757]])

In [20]:
rd.randint(1, 101, size = [3, 5])

array([[ 30,  63,   5,  95,  88],
       [ 54,  13,  79,  24,  28],
       [ 43, 100,  41,  42,  58]])

In [21]:
rd.uniform(1, 101, size = [3, 5])

array([[69.89455771, 12.78084274, 14.40895519, 76.10655456, 74.1200824 ],
       [ 1.57645361, 22.09812658, 32.73460663, 68.53171827, 97.1459118 ],
       [17.68643255, 20.31660451, 89.84134549, 94.69951234, 22.78264888]])

In [22]:
x = np.array([5,5,4,5,2,47,5,2], ndmin=15)
print(x)

[[[[[[[[[[[[[[[ 5  5  4  5  2 47  5  2]]]]]]]]]]]]]]]


In [23]:
np.argmin(x)

4

In [24]:
np.argmax(x)

5