In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy.random as rd

----------------

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.shape(arr)

(3, 3)

In [4]:
arr = np.arange(1,25).reshape(4, 3, 2)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [5]:
arr = np.zeros((3, 4), dtype=str)
arr

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [6]:
arr = np.ones((3,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
arr = rd.randint(1, 101, size = [2, 10, 15])
print(arr)

[[[ 33  48  56  23  87  89  56  55  11  18  66  29  92  38  36]
  [  6  45  79  71  86  41  61   1  96  88  68  84  17  80 100]
  [ 99  46  89  50  98  11  45  31  75  64  14  87  20  92  46]
  [ 82  20  87   8  39  59  96  87  45  12  25  80  99  80  14]
  [ 96  12   3  34  54  46  24  10   2  23  92  23  24  64  86]
  [ 51  52  37  83  58  46  90   5  53  46  50  36  91  80  10]
  [ 65  27  70  14  98   3  72  16  48  10  36  70  63  95  50]
  [ 26  15  24  41  70  84  34   4  52  34  37  88  16  11  25]
  [ 23  26  30  53  75  32  10  60  34  65   7  29  21  31  99]
  [ 81  33   4  88  99  66  43  92  52  63   9  24  77  68  55]]

 [[ 32  62  34  41  71  56  97  84  11  43  57  84   3  60  20]
  [ 73   5  23   1  69  46  39  67  33  37  91  19  90  58  15]
  [ 31  31  44  10  15  15  34  69  66  32  38  34  29  60  49]
  [ 62  19  21  99  90   5  44  85  74  77  13  82  32  65  70]
  [ 62  75  44  42  61  72  87  29  56  59 100  40  13  98  31]
  [ 99  25  87  36  69  99  47  28  73

In [8]:
arr1 = rd.randint(1, 101, size = [5,7])
print(arr1)

[[51 50 89  1 77 45 15]
 [78  1 22 64 88 48 21]
 [16  7 27 93 41 77 46]
 [33 21 13 81 82 92 43]
 [ 5 13 94 97 57 42 60]]


In [9]:
arr1 = rd.choice(np.arange(101), size = [3, 3, 4, 4])
print(arr1)

[[[[ 98  69   9  56]
   [  2  54  24  15]
   [ 92  79  41  38]
   [ 77  51 100   3]]

  [[ 67  75  65  53]
   [ 76  50  32  83]
   [ 22  79  84  45]
   [ 51  40  21  40]]

  [[ 74  64   3  46]
   [ 52  79  24  42]
   [ 88  91  24  82]
   [ 64  58  39  45]]]


 [[[ 61  42  35  61]
   [ 69  48  64  41]
   [ 67  70  75  80]
   [ 22  89  87  95]]

  [[ 91   8  35   7]
   [ 80  95  80  19]
   [ 76  55  40  94]
   [ 52  22  39  14]]

  [[ 86  65  42  25]
   [ 45  41  34  64]
   [ 74   4  28  13]
   [ 80  22  32  11]]]


 [[[ 13  51  10  46]
   [ 91  19  69  93]
   [ 60  10  70  67]
   [ 44  69  66  11]]

  [[ 23  28   3  91]
   [ 12  38  78  35]
   [ 98  76  45   4]
   [ 60  55  27   5]]

  [[ 62  53  99  80]
   [ 82  78  96  62]
   [ 25  67  37  68]
   [ 44  90  16  41]]]]


In [10]:
rd.choice(arr1.flatten(), size = [3, 4])

array([[62, 10, 24, 58],
       [28, 66, 80, 16],
       [25, 67, 65, 92]])

In [11]:
rd.rand(3,5)

array([[0.87766862, 0.61869859, 0.03866195, 0.93197896, 0.12815492],
       [0.80849356, 0.25342078, 0.04449664, 0.97040369, 0.23332433],
       [0.2829164 , 0.29620664, 0.04665303, 0.68062776, 0.60327348]])

In [12]:
rd.randint(1, 101, size = [3, 5])

array([[ 25,  80,  34,  91,  11],
       [ 92,  46,  20,  69,  58],
       [ 66,  58, 100,  98,  72]])

In [13]:
rd.uniform(1, 101, size = [3, 5])

array([[16.3683145 , 26.18873773, 75.20419211, 62.99365001,  8.95383064],
       [18.94914055, 98.81573355, 29.73282494, 75.78135722, 24.07408025],
       [20.80194804, 43.24505549, 41.46217231, 23.05965733, 83.22813518]])

In [14]:
x = np.array([54,85,46,95,21,47,35,29], ndmin=3, dtype=float)
print(x)

[[[54. 85. 46. 95. 21. 47. 35. 29.]]]


In [15]:
np.max(x)

95.0

In [16]:
np.min(x)

21.0

In [17]:
np.argmin(x)

4

In [18]:
np.argmax(x)

3

In [19]:
np.mean(arr)

51.24666666666667

In [20]:
np.median(arr)

50.0

In [21]:
np.std(arr)

28.933933173505615

In [22]:
np.var(arr)

837.1724888888888

In [23]:
np.power(x, x)

array([[[3.54211805e+093, 1.00140253e+164, 3.06803463e+076,
         7.65142812e+187, 5.84258702e+027, 3.87792426e+078,
         1.10250750e+054, 2.56768615e+042]]])

In [24]:
x = arr.flatten()
print(x)

[ 33  48  56  23  87  89  56  55  11  18  66  29  92  38  36   6  45  79
  71  86  41  61   1  96  88  68  84  17  80 100  99  46  89  50  98  11
  45  31  75  64  14  87  20  92  46  82  20  87   8  39  59  96  87  45
  12  25  80  99  80  14  96  12   3  34  54  46  24  10   2  23  92  23
  24  64  86  51  52  37  83  58  46  90   5  53  46  50  36  91  80  10
  65  27  70  14  98   3  72  16  48  10  36  70  63  95  50  26  15  24
  41  70  84  34   4  52  34  37  88  16  11  25  23  26  30  53  75  32
  10  60  34  65   7  29  21  31  99  81  33   4  88  99  66  43  92  52
  63   9  24  77  68  55  32  62  34  41  71  56  97  84  11  43  57  84
   3  60  20  73   5  23   1  69  46  39  67  33  37  91  19  90  58  15
  31  31  44  10  15  15  34  69  66  32  38  34  29  60  49  62  19  21
  99  90   5  44  85  74  77  13  82  32  65  70  62  75  44  42  61  72
  87  29  56  59 100  40  13  98  31  99  25  87  36  69  99  47  28  73
  35  23  23  48  96  48  55  69  89  75  11  72  9

In [25]:
np.sort(x)

array([  1,   1,   2,   3,   3,   3,   3,   4,   4,   4,   5,   5,   5,
         5,   6,   7,   7,   8,   9,  10,  10,  10,  10,  10,  11,  11,
        11,  11,  11,  11,  12,  12,  12,  13,  13,  13,  14,  14,  14,
        15,  15,  15,  15,  15,  16,  16,  16,  17,  18,  19,  19,  19,
        20,  20,  20,  20,  21,  21,  23,  23,  23,  23,  23,  23,  23,
        24,  24,  24,  24,  24,  25,  25,  25,  25,  26,  26,  27,  28,
        28,  29,  29,  29,  29,  30,  31,  31,  31,  31,  31,  32,  32,
        32,  32,  32,  33,  33,  33,  34,  34,  34,  34,  34,  34,  34,
        34,  35,  36,  36,  36,  36,  37,  37,  37,  38,  38,  38,  38,
        39,  39,  40,  41,  41,  41,  41,  42,  43,  43,  43,  44,  44,
        44,  45,  45,  45,  46,  46,  46,  46,  46,  46,  46,  47,  47,
        48,  48,  48,  48,  49,  49,  50,  50,  50,  50,  51,  51,  51,
        52,  52,  52,  53,  53,  54,  55,  55,  55,  56,  56,  56,  56,
        57,  58,  58,  59,  59,  60,  60,  60,  60,  61,  61,  6

In [26]:
(np.sort(x))[::-1]

array([100, 100,  99,  99,  99,  99,  99,  99,  99,  99,  98,  98,  98,
        97,  96,  96,  96,  96,  96,  95,  94,  93,  92,  92,  92,  92,
        92,  92,  92,  92,  91,  91,  90,  90,  90,  90,  89,  89,  89,
        89,  89,  88,  88,  88,  88,  87,  87,  87,  87,  87,  87,  87,
        86,  86,  85,  85,  84,  84,  84,  84,  83,  82,  82,  82,  82,
        81,  81,  80,  80,  80,  80,  79,  78,  77,  77,  76,  75,  75,
        75,  75,  74,  74,  73,  73,  72,  72,  72,  71,  71,  70,  70,
        70,  70,  70,  69,  69,  69,  69,  69,  68,  68,  67,  67,  66,
        66,  66,  66,  65,  65,  65,  65,  64,  64,  63,  63,  63,  62,
        62,  62,  61,  61,  61,  60,  60,  60,  60,  59,  59,  58,  58,
        57,  56,  56,  56,  56,  55,  55,  55,  54,  53,  53,  52,  52,
        52,  51,  51,  51,  50,  50,  50,  50,  49,  49,  48,  48,  48,
        48,  47,  47,  46,  46,  46,  46,  46,  46,  46,  45,  45,  45,
        44,  44,  44,  43,  43,  43,  42,  41,  41,  41,  41,  4

In [ ]:
x.reshape(1,-1) # one column, multiple rows

array([[ 33,  48,  56,  23,  87,  89,  56,  55,  11,  18,  66,  29,  92,
         38,  36,   6,  45,  79,  71,  86,  41,  61,   1,  96,  88,  68,
         84,  17,  80, 100,  99,  46,  89,  50,  98,  11,  45,  31,  75,
         64,  14,  87,  20,  92,  46,  82,  20,  87,   8,  39,  59,  96,
         87,  45,  12,  25,  80,  99,  80,  14,  96,  12,   3,  34,  54,
         46,  24,  10,   2,  23,  92,  23,  24,  64,  86,  51,  52,  37,
         83,  58,  46,  90,   5,  53,  46,  50,  36,  91,  80,  10,  65,
         27,  70,  14,  98,   3,  72,  16,  48,  10,  36,  70,  63,  95,
         50,  26,  15,  24,  41,  70,  84,  34,   4,  52,  34,  37,  88,
         16,  11,  25,  23,  26,  30,  53,  75,  32,  10,  60,  34,  65,
          7,  29,  21,  31,  99,  81,  33,   4,  88,  99,  66,  43,  92,
         52,  63,   9,  24,  77,  68,  55,  32,  62,  34,  41,  71,  56,
         97,  84,  11,  43,  57,  84,   3,  60,  20,  73,   5,  23,   1,
         69,  46,  39,  67,  33,  37,  91,  19,  90

In [ ]:
x.reshape(-1,1) # one row, multiple columns

array([[ 33],
       [ 48],
       [ 56],
       [ 23],
       [ 87],
       [ 89],
       [ 56],
       [ 55],
       [ 11],
       [ 18],
       [ 66],
       [ 29],
       [ 92],
       [ 38],
       [ 36],
       [  6],
       [ 45],
       [ 79],
       [ 71],
       [ 86],
       [ 41],
       [ 61],
       [  1],
       [ 96],
       [ 88],
       [ 68],
       [ 84],
       [ 17],
       [ 80],
       [100],
       [ 99],
       [ 46],
       [ 89],
       [ 50],
       [ 98],
       [ 11],
       [ 45],
       [ 31],
       [ 75],
       [ 64],
       [ 14],
       [ 87],
       [ 20],
       [ 92],
       [ 46],
       [ 82],
       [ 20],
       [ 87],
       [  8],
       [ 39],
       [ 59],
       [ 96],
       [ 87],
       [ 45],
       [ 12],
       [ 25],
       [ 80],
       [ 99],
       [ 80],
       [ 14],
       [ 96],
       [ 12],
       [  3],
       [ 34],
       [ 54],
       [ 46],
       [ 24],
       [ 10],
       [  2],
       [ 23],
       [ 92],
      

_______

In [78]:
ser1 = pd.Series([5,8,9,2,1,6], dtype=int)
ser1

0    5
1    8
2    9
3    2
4    1
5    6
dtype: int32

In [81]:
cars_names = pd.Series(["Audi", "Mercedes", "BMW", "Porsche", "Toyota", "Honda"], dtype=str)
cars_names

0        Audi
1    Mercedes
2         BMW
3     Porsche
4      Toyota
5       Honda
dtype: object

In [91]:
cars = pd.DataFrame({"Cars": cars_names, "Qtys": ser1})
cars

Cars  Qtys
0      Audi     5
1  Mercedes     8
2       BMW     9
3   Porsche     2
4    Toyota     1
5     Honda     6

In [92]:
cars.shape

(6, 2)

In [108]:
df = pd.DataFrame({
    "a": [1,2,3,4,5],
    "b": [2,4,6,8,10]
})
df

a   b
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10

In [109]:
df["c"] = df["a"] + df["b"]
df

a   b   c
0  1   2   3
1  2   4   6
2  3   6   9
3  4   8  12
4  5  10  15

In [111]:
df["d"] = df["a"] * (df["b"] + df["c"])
df

a   b   c    d
0  1   2   3    5
1  2   4   6   20
2  3   6   9   45
3  4   8  12   80
4  5  10  15  125

In [119]:
df.insert(2, "e", [11,15,17,19,21])

In [120]:
df

a   b   e   c    d
0  1   2  11   3    5
1  2   4  15   6   20
2  3   6  17   9   45
3  4   8  19  12   80
4  5  10  21  15  125