In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy.random as rd

----------------

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.shape(arr)

(3, 3)

In [4]:
arr = np.arange(1,25).reshape(4, 3, 2)
print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [5]:
arr = np.zeros((3, 4), dtype=str)
arr

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [6]:
arr = np.ones((3,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
arr = rd.randint(1, 101, size = [2, 10, 15])
print(arr)

[[[ 73   9  56  66  76  63  92  36  13  23  57  15  27  41  94]
  [ 14  77  32  54   5  35   7  12  44   7  82  61   7  94  98]
  [ 28  36  29   5  29  68  65  70  62  81  82  63  75  81  42]
  [ 46  99  45  35  45  48  56  19  63  16  59  26  98  92  42]
  [ 44  93  92  20  34  97  37  37  57  60  68  98  48  34  62]
  [100  21  55   3   6  32  53  82  19  59  95  62   1  42  61]
  [  1  66  62  54  56  96  61   5  14  63  83  28  96  19  72]
  [ 30  25  16   9  62  79  75   2  59  28  17  62  80  77  90]
  [  6   5  21  32  59  20  24  44  62  28  50  36  53  22  21]
  [ 19  86  64   4  32  57  48  80  39   2  37  93  45  73  31]]

 [[ 55  89  86  94  10  24  41  58   1   5  92  46  92  94  28]
  [ 54  83  25   5  57  32  14  28  98  72   6  44  98  66  54]
  [ 86  78  79  82  71  56   2   4  97  78  49  20  29  29  87]
  [ 62  22  16  47   3  60  63   8  39  31  22  32  42  37  57]
  [ 78  41   6  46  50  21  18  77  61  22  14  86  84  24  40]
  [ 82  81  73   6  88  89  69  93  26

In [8]:
arr1 = rd.randint(1, 101, size = [5,7])
print(arr1)

[[ 57  53   9 100  67  52  51]
 [ 29  44  56  88  59  36  83]
 [ 19  10  74  75  96  54  37]
 [  1  42  40  40   9  68  14]
 [ 81  70  13  65  47  93  70]]


In [9]:
arr1 = rd.choice(np.arange(101), size = [3, 3, 4, 4])
print(arr1)

[[[[ 90  61  91  26]
   [  5  46  58  20]
   [ 62  16 100  83]
   [ 86  47  33  71]]

  [[  9  12  81   6]
   [ 28  27  58  87]
   [ 47   6  83  93]
   [ 93  55  13  63]]

  [[ 73  84  47  18]
   [ 44  81  79  68]
   [ 18  63  22  23]
   [ 38   6  94  16]]]


 [[[ 88  41  65  81]
   [ 38  97  62  40]
   [ 62  31  44  56]
   [ 43  43  67  42]]

  [[ 10  54  61  49]
   [ 92   9  46  82]
   [ 24  20  49  25]
   [  6  91  23  97]]

  [[ 89  56  67  98]
   [  8  57   3   8]
   [ 76  69  53  93]
   [ 56  53  40  82]]]


 [[[ 14  83  43   2]
   [ 98   0  63  44]
   [ 21  87  29  68]
   [ 70   1  58  94]]

  [[ 60  83  79  85]
   [ 29  21  77  51]
   [ 23  94  20   6]
   [  5   9  38   0]]

  [[ 61  85  92  62]
   [ 57  79  74  96]
   [ 79  71  41  59]
   [ 55  67   5  34]]]]


In [10]:
rd.choice(arr1.flatten(), size = [3, 4])

array([[81, 58, 84, 59],
       [25, 23, 81, 71],
       [91, 43, 57, 67]])

In [11]:
rd.rand(3,5)

array([[0.00526981, 0.88657043, 0.50809502, 0.08424573, 0.27723816],
       [0.88762315, 0.5401044 , 0.48711437, 0.55691082, 0.69433727],
       [0.91698222, 0.51757637, 0.59084301, 0.98319998, 0.26474695]])

In [12]:
rd.randint(1, 101, size = [3, 5])

array([[83, 99, 99, 67, 82],
       [61, 85, 92,  1, 23],
       [53, 87, 93, 70, 26]])

In [13]:
rd.uniform(1, 101, size = [3, 5])

array([[98.66780497, 62.17633641, 14.68466612, 12.5588043 , 85.08659457],
       [65.24535637, 63.04007711, 12.44313844, 18.06197186, 88.45001709],
       [20.52909286, 20.766995  , 18.58527872, 28.04567949, 40.73506953]])

In [14]:
x = np.array([54,85,46,95,21,47,35,29], ndmin=3, dtype=float)
print(x)

[[[54. 85. 46. 95. 21. 47. 35. 29.]]]


In [15]:
np.max(x)

95.0

In [16]:
np.min(x)

21.0

In [17]:
np.argmin(x)

4

In [18]:
np.argmax(x)

3

In [19]:
np.mean(arr)

50.973333333333336

In [20]:
np.median(arr)

54.0

In [21]:
np.std(arr)

28.642845916951448

In [22]:
np.var(arr)

820.4126222222222

In [23]:
np.power(x, x)

array([[[3.54211805e+093, 1.00140253e+164, 3.06803463e+076,
         7.65142812e+187, 5.84258702e+027, 3.87792426e+078,
         1.10250750e+054, 2.56768615e+042]]])

In [24]:
x = arr.flatten()
print(x)

[ 73   9  56  66  76  63  92  36  13  23  57  15  27  41  94  14  77  32
  54   5  35   7  12  44   7  82  61   7  94  98  28  36  29   5  29  68
  65  70  62  81  82  63  75  81  42  46  99  45  35  45  48  56  19  63
  16  59  26  98  92  42  44  93  92  20  34  97  37  37  57  60  68  98
  48  34  62 100  21  55   3   6  32  53  82  19  59  95  62   1  42  61
   1  66  62  54  56  96  61   5  14  63  83  28  96  19  72  30  25  16
   9  62  79  75   2  59  28  17  62  80  77  90   6   5  21  32  59  20
  24  44  62  28  50  36  53  22  21  19  86  64   4  32  57  48  80  39
   2  37  93  45  73  31  55  89  86  94  10  24  41  58   1   5  92  46
  92  94  28  54  83  25   5  57  32  14  28  98  72   6  44  98  66  54
  86  78  79  82  71  56   2   4  97  78  49  20  29  29  87  62  22  16
  47   3  60  63   8  39  31  22  32  42  37  57  78  41   6  46  50  21
  18  77  61  22  14  86  84  24  40  82  81  73   6  88  89  69  93  26
  63  73  84  84  39  44  85  35  37  60  20 100  9

In [25]:
np.sort(x)

array([  1,   1,   1,   2,   2,   2,   3,   3,   3,   4,   4,   5,   5,
         5,   5,   5,   5,   6,   6,   6,   6,   6,   6,   7,   7,   7,
         8,   9,   9,  10,  10,  11,  12,  13,  14,  14,  14,  14,  14,
        15,  16,  16,  16,  16,  16,  17,  18,  18,  19,  19,  19,  19,
        20,  20,  20,  20,  21,  21,  21,  21,  22,  22,  22,  22,  23,
        24,  24,  24,  24,  24,  25,  25,  26,  26,  27,  28,  28,  28,
        28,  28,  28,  29,  29,  29,  29,  30,  30,  31,  31,  32,  32,
        32,  32,  32,  32,  34,  34,  35,  35,  35,  35,  36,  36,  36,
        36,  37,  37,  37,  37,  37,  39,  39,  39,  40,  41,  41,  41,
        41,  42,  42,  42,  42,  42,  43,  44,  44,  44,  44,  44,  44,
        45,  45,  45,  45,  46,  46,  46,  46,  47,  47,  48,  48,  48,
        49,  50,  50,  53,  53,  54,  54,  54,  54,  54,  55,  55,  55,
        55,  56,  56,  56,  56,  56,  56,  57,  57,  57,  57,  57,  58,
        59,  59,  59,  59,  60,  60,  60,  60,  60,  61,  61,  6

In [26]:
(np.sort(x))[::-1]

array([100, 100, 100,  99,  98,  98,  98,  98,  98,  98,  97,  97,  96,
        96,  95,  95,  95,  95,  95,  94,  94,  94,  94,  94,  93,  93,
        93,  93,  92,  92,  92,  92,  92,  92,  90,  90,  89,  89,  88,
        87,  86,  86,  86,  86,  86,  85,  84,  84,  84,  84,  83,  83,
        83,  82,  82,  82,  82,  82,  81,  81,  81,  81,  80,  80,  79,
        79,  79,  78,  78,  78,  77,  77,  77,  76,  75,  75,  73,  73,
        73,  73,  73,  73,  73,  72,  72,  72,  71,  71,  70,  70,  69,
        69,  68,  68,  66,  66,  66,  65,  65,  64,  64,  64,  64,  63,
        63,  63,  63,  63,  63,  62,  62,  62,  62,  62,  62,  62,  62,
        62,  61,  61,  61,  61,  60,  60,  60,  60,  60,  59,  59,  59,
        59,  58,  57,  57,  57,  57,  57,  56,  56,  56,  56,  56,  56,
        55,  55,  55,  55,  54,  54,  54,  54,  54,  53,  53,  50,  50,
        49,  48,  48,  48,  47,  47,  46,  46,  46,  46,  45,  45,  45,
        45,  44,  44,  44,  44,  44,  44,  43,  42,  42,  42,  4

In [27]:
x.reshape(1,-1) # one column, multiple rows

array([[ 73,   9,  56,  66,  76,  63,  92,  36,  13,  23,  57,  15,  27,
         41,  94,  14,  77,  32,  54,   5,  35,   7,  12,  44,   7,  82,
         61,   7,  94,  98,  28,  36,  29,   5,  29,  68,  65,  70,  62,
         81,  82,  63,  75,  81,  42,  46,  99,  45,  35,  45,  48,  56,
         19,  63,  16,  59,  26,  98,  92,  42,  44,  93,  92,  20,  34,
         97,  37,  37,  57,  60,  68,  98,  48,  34,  62, 100,  21,  55,
          3,   6,  32,  53,  82,  19,  59,  95,  62,   1,  42,  61,   1,
         66,  62,  54,  56,  96,  61,   5,  14,  63,  83,  28,  96,  19,
         72,  30,  25,  16,   9,  62,  79,  75,   2,  59,  28,  17,  62,
         80,  77,  90,   6,   5,  21,  32,  59,  20,  24,  44,  62,  28,
         50,  36,  53,  22,  21,  19,  86,  64,   4,  32,  57,  48,  80,
         39,   2,  37,  93,  45,  73,  31,  55,  89,  86,  94,  10,  24,
         41,  58,   1,   5,  92,  46,  92,  94,  28,  54,  83,  25,   5,
         57,  32,  14,  28,  98,  72,   6,  44,  98

In [28]:
x.reshape(-1,1) # one row, multiple columns

array([[ 73],
       [  9],
       [ 56],
       [ 66],
       [ 76],
       [ 63],
       [ 92],
       [ 36],
       [ 13],
       [ 23],
       [ 57],
       [ 15],
       [ 27],
       [ 41],
       [ 94],
       [ 14],
       [ 77],
       [ 32],
       [ 54],
       [  5],
       [ 35],
       [  7],
       [ 12],
       [ 44],
       [  7],
       [ 82],
       [ 61],
       [  7],
       [ 94],
       [ 98],
       [ 28],
       [ 36],
       [ 29],
       [  5],
       [ 29],
       [ 68],
       [ 65],
       [ 70],
       [ 62],
       [ 81],
       [ 82],
       [ 63],
       [ 75],
       [ 81],
       [ 42],
       [ 46],
       [ 99],
       [ 45],
       [ 35],
       [ 45],
       [ 48],
       [ 56],
       [ 19],
       [ 63],
       [ 16],
       [ 59],
       [ 26],
       [ 98],
       [ 92],
       [ 42],
       [ 44],
       [ 93],
       [ 92],
       [ 20],
       [ 34],
       [ 97],
       [ 37],
       [ 37],
       [ 57],
       [ 60],
       [ 68],
      

_______

In [29]:
ser1 = pd.Series([5,8,9,2,1,6], dtype=int)
ser1

0    5
1    8
2    9
3    2
4    1
5    6
dtype: int32

In [30]:
cars_names = pd.Series(["Audi", "Mercedes", "BMW", "Porsche", "Toyota", "Honda"], dtype=str)
cars_names

0        Audi
1    Mercedes
2         BMW
3     Porsche
4      Toyota
5       Honda
dtype: object

In [31]:
cars = pd.DataFrame({"Cars": cars_names, "Qtys": ser1})
cars

Cars  Qtys
0      Audi     5
1  Mercedes     8
2       BMW     9
3   Porsche     2
4    Toyota     1
5     Honda     6

In [32]:
cars.shape

(6, 2)

In [33]:
df = pd.DataFrame({
    "a": [1,2,3,4,5],
    "b": [2,4,6,8,10]
})
df

a   b
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10

In [34]:
df["c"] = df["a"] + df["b"]
df

a   b   c
0  1   2   3
1  2   4   6
2  3   6   9
3  4   8  12
4  5  10  15

In [35]:
df["d"] = df["a"] * (df["b"] + df["c"])
df

a   b   c    d
0  1   2   3    5
1  2   4   6   20
2  3   6   9   45
3  4   8  12   80
4  5  10  15  125

In [36]:
df.insert(2, "e", [11,15,17,19,21])

In [37]:
df

a   b   e   c    d
0  1   2  11   3    5
1  2   4  15   6   20
2  3   6  17   9   45
3  4   8  19  12   80
4  5  10  21  15  125

In [ ]:
df = pd.read_csv("petrol_consumption.csv")
df.head()

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.0            3571            1976                         0.525   
1         9.0            4092            1250                         0.572   
2         9.0            3865            1586                         0.580   
3         7.5            4870            2351                         0.529   
4         8.0            4399             431                         0.544   

   Petrol_Consumption  
0                 541  
1                 524  
2                 561  
3                 414  
4                 410

In [ ]:
df.info() # -> describes the baisc info about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Petrol_tax                    48 non-null     float64
 1   Average_income                48 non-null     int64  
 2   Paved_Highways                48 non-null     int64  
 3   Population_Driver_licence(%)  48 non-null     float64
 4   Petrol_Consumption            48 non-null     int64  
dtypes: float64(2), int64(3)
memory usage: 2.0 KB


In [ ]:
df.describe() # -> statistical description and info about the dataset

Petrol_tax  Average_income  Paved_Highways  \
count   48.000000       48.000000       48.000000   
mean     7.668333     4241.833333     5565.416667   
std      0.950770      573.623768     3491.507166   
min      5.000000     3063.000000      431.000000   
25%      7.000000     3739.000000     3110.250000   
50%      7.500000     4298.000000     4735.500000   
75%      8.125000     4578.750000     7156.000000   
max     10.000000     5342.000000    17782.000000   

       Population_Driver_licence(%)  Petrol_Consumption  
count                     48.000000           48.000000  
mean                       0.570333          576.770833  
std                        0.055470          111.885816  
min                        0.451000          344.000000  
25%                        0.529750          509.500000  
50%                        0.564500          568.500000  
75%                        0.595250          632.750000  
max                        0.724000          968.000000

In [ ]:
df.loc[7:12, ["Petrol_tax", "Petrol_Consumption", "Average_income"]] # gets the desried columns, with rows as a slice - start & stop both included

Petrol_tax  Petrol_Consumption  Average_income
7          8.0                 467            5126
8          8.0                 464            4447
9          7.0                 498            4512
10         8.0                 580            4391
11         7.5                 471            5126
12         7.0                 525            4817

In [ ]:
df.iloc[7:12, 2:4] # gets the slice of the columns, with rows as a slice - stop not included

Paved_Highways  Population_Driver_licence(%)
7             2138                         0.553
8             8577                         0.529
9             8507                         0.552
10            5939                         0.530
11           14186                         0.525

In [52]:
df[["Petrol_tax", "Petrol_Consumption", "Average_income"]][7:15] # a simpler but less effective way to get a slice

Petrol_tax  Petrol_Consumption  Average_income
7          8.0                 467            5126
8          8.0                 464            4447
9          7.0                 498            4512
10         8.0                 580            4391
11         7.5                 471            5126
12         7.0                 525            4817
13         7.0                 508            4207
14         7.0                 566            4332